########################################################################################
# WAVIN SENTIO V2 - EXAMPLE CONFIGURATION                                              #
# This example shows how to configure the new Wavin Sentio v2 component                #
########################################################################################

substitutions:
  device_name: wavin-sentio
  friendly_name: "Wavin Sentio"
  
  # UART / RS-485 wiring
  rx_pin: 20
  tx_pin: 21
  
  # Wi-Fi
  ssid_set: !secret wifi_ssid
  password_set: !secret wifi_password

  # Friendly names for channels (up to 16)
  channel_01_friendly_name: Bryggers Bad
  channel_02_friendly_name: Bryggers
  channel_03_friendly_name: Entre Bad
  channel_04_friendly_name: Stuen

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO  # Set to DEBUG for troubleshooting
  logs:
    wavin_sentio: INFO
    modbus_controller: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret heater_api_key

ota:
  - platform: esphome
    password: !secret heater_ota

wifi:
  ssid: ${ssid_set}
  password: ${password_set}
  ap:
    ssid: "Wavin Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:

# RS485 / Modbus Configuration
uart:
  id: uart_sentio
  rx_pin: ${rx_pin}
  tx_pin: ${tx_pin}
  baud_rate: 19200
  parity: NONE
  stop_bits: 1

modbus:
  id: modbus_sentio
  uart_id: uart_sentio

modbus_controller:
  id: sentio_controller
  address: 0x01
  modbus_id: modbus_sentio
  update_interval: 10s
  command_throttle: 500ms

# External Component - Wavin Sentio v2
external_components:
  - source: github://JannicSJensen/Wavin_Sentio
    components: [wavin_sentio]
    refresh: 0s

# Wavin Sentio Component Configuration
wavin_sentio:
  id: sentio
  modbus_id: modbus_sentio
  update_interval: 10s
  poll_channels_per_cycle: 2  # Poll 2 channels per update cycle
  
  # Friendly names for channels (up to 16)
  channel_01_friendly_name: ${channel_01_friendly_name}
  channel_02_friendly_name: ${channel_02_friendly_name}
  channel_03_friendly_name: ${channel_03_friendly_name}
  channel_04_friendly_name: ${channel_04_friendly_name}
  # Add more as needed...

# Climate Entities
climate:
  # Single channel climates
  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_01_friendly_name}"
    channel: 1

  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_02_friendly_name}"
    channel: 2

  # Group climate (combines Living Room + Kitchen)
  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_03_friendly_name}"
    members: 3

  # Comfort climate (uses floor temperature for Bathroom)
  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_04_friendly_name}"
    channel: 4
    use_floor_temperature: true

# Sensors
sensor:
  # Battery sensors
  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_01_friendly_name} Battery"
    channel: 1
    type: battery

  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_02_friendly_name} Battery"
    channel: 2
    type: battery

  # Temperature sensors
  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_01_friendly_name} Temperature"
    channel: 1
    type: temperature

  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_02_friendly_name} Temperature"
    channel: 2
    type: temperature

  # Floor temperature (only if floor probe detected)
  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_01_friendly_name} Floor Temperature"
    channel: 1
    type: floor_temperature

  # Comfort setpoint (read-only)
  - platform: wavin_sentio
    wavin_sentio_id: sentio
    name: "${channel_01_friendly_name} Setpoint"
    channel: 1
    type: comfort_setpoint

